version: '3.1'

services:
  # db:
  #   image: mysql:8.0
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 12345678@Abc 
  #     MYSQL_DATABASE: testdb
  #     MYSQL_USER: user_testdb
  #     MYSQL_PASSWORD: 12345678@Abc
  frontend:
    image: frontend
    build: 
      context: ./my-blog
    ports:
      - "80:80"
    networks: 
      - my-networks
  backend:
    image: backend
    build:
      context: ./MyBlog
    ports:
      - "90:90"
    networks: 
      - my-networks
networks: 
  my-networks:
  # db:
# volumes:
#   db_mysql: