version: '3.1'

services:
  frontend:
    image: frontend
    build: 
      context: ./my-blog
    env_file:
      - ./my-blog/.env.production
    environment:
     - BACKEND_HOST_BASE=${BACKEND_HOST_BASE}
    restart: always
    ports:
      - "80:80"
    networks: 
      - my_network

  backend:
    image: backend
    build:
      context: ./MyBlog
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNET_CORE_ENVIRONMENT=Production
    networks: 
      - my_network

networks: 
  my_network: